import mongoose from "mongoose";
import Product from "../models/Product.js";

const PRODUCTS = [
    {
        _id: "6683d3d47f779795ecfa98a3",
        name: "Men Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 80,
        images: [
            "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img2_1.png",
            "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img2_2.png",
            "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img2_3.png",
            "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img2_4.png",
        ],
        category: "Men",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d5417f779795ecfa98b3",
        name: "Men Tapered Fit Flat-Front Trousers",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 72,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img10.png"],
        category: "Men",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d8097f779795ecfa98d9",
        name: "Women Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 36,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img5.png"],
        category: "Women",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d4937f779795ecfa98a9",
        name: "Women Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 30,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img29.png"],
        category: "Women",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d4d97f779795ecfa98ad",
        name: "Men Tapered Fit Flat-Front Trousers",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 70,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img7.png"],
        category: "Men",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683da5f7f779795ecfa98f9",
        name: "Men Slim Fit Relaxed Denim Jacket",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 86,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img45.png"],
        category: "Men",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: true,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683dac47f779795ecfa9901",
        name: "Kid Tapered Slim Fit Trouser",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 56,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img49.png"],
        category: "Kids",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d71c7f779795ecfa98cd",
        name: "Boy Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 26,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img23.png"],
        category: "Kids",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d9847f779795ecfa98ef",
        name: "Men Slim Fit Relaxed Denim Jacket",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 77,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img40.png"],
        category: "Men",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d9d07f779795ecfa98f3",
        name: "Boy Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 25,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img18.png"],
        category: "Kids",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d5217f779795ecfa98b1",
        name: "Girls Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 64,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img9.png"],
        category: "Kids",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d6a57f779795ecfa98c7",
        name: "Women Palazzo Pants with Waist Belt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 52,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img20.png"],
        category: "Women",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d9b27f779795ecfa98f1",
        name: "Men Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 54,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img41.png"],
        category: "Men",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d7737f779795ecfa98d1",
        name: "Girls Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 60,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img25.png"],
        category: "Kids",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d6887f779795ecfa98c5",
        name: "Boy Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 36,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img19.png"],
        category: "Kids",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d82b7f779795ecfa98db",
        name: "Girls Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 42,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img6.png"],
        category: "Kids",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d5647f779795ecfa98b5",
        name: "Men Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 46,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img11.png"],
        category: "Men",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d89d7f779795ecfa98e1",
        name: "Girls Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 48,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img9.png"],
        category: "Kids",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683da147f779795ecfa98f7",
        name: "Women Zip-Front Relaxed Fit Jacket",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 78,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img44.png"],
        category: "Women",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: true,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d91f7f779795ecfa98eb",
        name: "Men Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 48,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img14.png"],
        category: "Men",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683db0d7f779795ecfa9907",
        name: "Men Slim Fit Relaxed Denim Jacket",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 84,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img52.png"],
        category: "Men",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: true,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d42b7f779795ecfa98a5",
        name: "Girls Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 50,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img3.png"],
        category: "Kids",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d6dc7f779795ecfa98cb",
        name: "Women Palazzo Pants with Waist Belt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 67,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img22.png"],
        category: "Women",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d5987f779795ecfa98b9",
        name: "Women Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 45,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img13.png"],
        category: "Women",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d6057f779795ecfa98bf",
        name: "Girls Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 40,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img16.png"],
        category: "Kids",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d8467f779795ecfa98dd",
        name: "Men Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 34,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img31.png"],
        category: "Men",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d90a7f779795ecfa98e9",
        name: "Women Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 42,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img13.png"],
        category: "Women",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d9fa7f779795ecfa98f5",
        name: "Kid Tapered Slim Fit Trouser",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 60,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img43.png"],
        category: "Kids",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683daa27f779795ecfa98ff",
        name: "Men Slim Fit Relaxed Denim Jacket",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 80,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img48.png"],
        category: "Men",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d8b37f779795ecfa98e3",
        name: "Women Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 38,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img34.png"],
        category: "Women",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d6547f779795ecfa98c3",
        name: "Boy Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 28,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img18.png"],
        category: "Kids",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d4f47f779795ecfa98af",
        name: "Men Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 68,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img8.png"],
        category: "Men",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d57d7f779795ecfa98b7",
        name: "Men Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 26,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img12.png"],
        category: "Men",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d6387f779795ecfa98c1",
        name: "Men Tapered Fit Flat-Front Trousers",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 63,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img17.png"],
        category: "Men",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d6c47f779795ecfa98c9",
        name: "Women Zip-Front Relaxed Fit Jacket",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 82,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img21.png"],
        category: "Women",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683da717f779795ecfa98fb",
        name: "Men Slim Fit Relaxed Denim Jacket",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 72,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img46.png"],
        category: "Men",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: true,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d7b57f779795ecfa98d5",
        name: "Girls Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 38,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img3.png"],
        category: "Kids",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d3947f779795ecfa98a1",
        name: "Women Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 40,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img1.png"],
        category: "Women",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d4587f779795ecfa98a7",
        name: "Men Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 26,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img4.png"],
        category: "Men",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d7567f779795ecfa98cf",
        name: "Boy Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 30,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img24.png"],
        category: "Kids",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d79e7f779795ecfa98d3",
        name: "Women Zip-Front Relaxed Fit Jacket",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 82,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img26.png"],
        category: "Women",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d7d57f779795ecfa98d7",
        name: "Men Slim Fit Relaxed Denim Jacket",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 79,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img28.png"],
        category: "Men",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d8f27f779795ecfa98e7",
        name: "Women Zip-Front Relaxed Fit Jacket",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 78,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img36.png"],
        category: "Women",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d94e7f779795ecfa98ed",
        name: "Men Printed Plain Cotton Shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 52,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img39.png"],
        category: "Men",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683dadf7f779795ecfa9903",
        name: "Kid Tapered Slim Fit Trouser",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 40,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img50.png"],
        category: "Kids",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683daf67f779795ecfa9905",
        name: "Women Zip-Front Relaxed Fit Jacket",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 68,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img51.png"],
        category: "Women",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: true,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d4b27f779795ecfa98ab",
        name: "Girls Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 56,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img6.png"],
        category: "Kids",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d5e07f779795ecfa98bd",
        name: "Men Tapered Fit Flat-Front Trousers",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 58,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img15.png"],
        category: "Men",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d8d17f779795ecfa98e5",
        name: "Women Zip-Front Relaxed Fit Jacket",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 74,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img35.png"],
        category: "Women",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d5b67f779795ecfa98bb",
        name: "Boy Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 60,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img14.png"],
        category: "Kids",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683d8897f779795ecfa98df",
        name: "Men Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 64,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img8.png"],
        category: "Men",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
    {
        _id: "6683da887f779795ecfa98fd",
        name: "Kid Tapered Slim Fit Trouser",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 38,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img47.png"],
        category: "Kids",
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 100,
        isActive: true,
        ratings: {
            average: 0,
            count: 0,
        },
        isFeatured: false,
        date: 1719915311964,
        __v: 0,
    },
];

export const seedProducts = async (uri: string) => {
    try {
        await mongoose.connect(uri);
        const products = await Product.find();
        if (products.length === 0) {
            await Product.insertMany(PRODUCTS);
        } else {
            console.log("Products already exist");
        }
    } catch (error) {
        console.error("Seeding Error:", error);
    }
};
