export const BANNERS = [
    {
        id: 1,
        image: "https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=1000&auto=format&fit=crop",
        title: "50% Off",
        subtitle: "On everything today",
    },
    {
        id: 2,
        image: "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?q=80&w=1000&auto=format&fit=crop",
        title: "New Arrivals",
        subtitle: "Summer Collection 2024",
    },
    {
        id: 3,
        image: "https://images.unsplash.com/photo-1445205170230-053b83016050?q=80&w=1000&auto=format&fit=crop",
        title: "Big Sale",
        subtitle: "Up to 70% off shoes",
    },
];

export const formatDate = (dateString: string) => {
    const options: Intl.DateTimeFormatOptions = { year: "numeric", month: "short", day: "numeric" };
    return new Date(dateString).toLocaleDateString(undefined, options);
};

export const dummyProducts = [
    {
        ratings: {
            average: 4.7,
            count: 95,
        },
        _id: "698442cfda74ab16485b6060",
        name: "Summer Dress",
        description: "Light and airy summer dress with a floral pattern.",
        price: 55,
        images: ["https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=1000&auto=format&fit=crop"],
        sizes: ["XS", "S", "M", "L"],
        category: "Women",
        stock: 45,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-05T07:12:15.825Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683db0d7f779795ecfa9907",
        name: "Men Slim Fit Relaxed Denim Jacket",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 84,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img52.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Men",
        stock: 61,
        isFeatured: true,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 4.6,
            count: 50,
        },
        _id: "698442cfda74ab16485b6061",
        name: "Running Shoes",
        description: "Lightweight running shoes designed for speed and comfort.",
        price: 79.99,
        comparePrice: 99.99,
        images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1000&auto=format&fit=crop"],
        sizes: ["9"],
        category: "Shoes",
        stock: 14,
        isFeatured: true,
        isActive: true,
        createdAt: "2026-02-05T07:12:15.825Z",
    },
    {
        ratings: {
            average: 4.9,
            count: 200,
        },
        _id: "698442cfda74ab16485b605f",
        name: "Denim Jacket",
        description: "Classic denim jacket that goes with everything. Durable and stylish.",
        price: 89.99,
        images: ["https://images.unsplash.com/photo-1559551409-dadc959f76b8?q=80&w=1000&auto=format&fit=crop"],
        sizes: ["S", "M", "L", "XL"],
        category: "Men",
        stock: 20,
        isFeatured: true,
        isActive: true,
        createdAt: "2026-02-05T07:12:15.824Z",
    },
    {
        ratings: {
            average: 4.5,
            count: 85,
        },
        _id: "698442cfda74ab16485b605e",
        name: "Casual Hoodie",
        description: "Comfortable hoodie for everyday wear. Soft cotton fabric with a relaxed fit.",
        price: 45,
        comparePrice: 60,
        images: ["https://images.unsplash.com/photo-1556905055-8f358a7a47b2?q=80&w=1000&auto=format&fit=crop"],
        sizes: ["M", "L", "XL", "XXL"],
        category: "Men",
        stock: 29,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-05T07:12:15.824Z",
    },
    {
        ratings: {
            average: 4.9,
            count: 30,
        },
        _id: "698442cfda74ab16485b6062",
        name: "Leather Bag",
        description: "Premium leather bag with ample storage.",
        price: 129.99,
        images: ["https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=1000&auto=format&fit=crop"],
        sizes: ["One Size"],
        category: "Bags",
        stock: 9,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-05T07:12:15.825Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d3d47f779795ecfa98a3",
        name: "Men Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 80,
        images: [
            "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img2_1.png",
            "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img2_2.png",
            "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img2_3.png",
            "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img2_4.png",
        ],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Men",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d5417f779795ecfa98b3",
        name: "Men Tapered Fit Flat-Front Trousers",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 72,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img10.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Men",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d8097f779795ecfa98d9",
        name: "Women Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 36,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img5.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Women",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d4937f779795ecfa98a9",
        name: "Women Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 30,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img29.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Women",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d4d97f779795ecfa98ad",
        name: "Men Tapered Fit Flat-Front Trousers",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 70,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img7.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Men",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683da5f7f779795ecfa98f9",
        name: "Men Slim Fit Relaxed Denim Jacket",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 86,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img45.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Men",
        stock: 100,
        isFeatured: true,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683dac47f779795ecfa9901",
        name: "Kid Tapered Slim Fit Trouser",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 56,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img49.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kids",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d71c7f779795ecfa98cd",
        name: "Boy Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 26,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img23.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kids",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d9847f779795ecfa98ef",
        name: "Men Slim Fit Relaxed Denim Jacket",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 77,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img40.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Men",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d9d07f779795ecfa98f3",
        name: "Boy Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 25,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img18.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kids",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d5217f779795ecfa98b1",
        name: "Girls Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 64,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img9.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kids",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d6a57f779795ecfa98c7",
        name: "Women Palazzo Pants with Waist Belt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 52,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img20.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Women",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d9b27f779795ecfa98f1",
        name: "Men Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 54,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img41.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Men",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d7737f779795ecfa98d1",
        name: "Girls Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 60,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img25.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kids",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d6887f779795ecfa98c5",
        name: "Boy Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 36,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img19.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kids",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d82b7f779795ecfa98db",
        name: "Girls Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 42,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img6.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kids",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d5647f779795ecfa98b5",
        name: "Men Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 46,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img11.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Men",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d89d7f779795ecfa98e1",
        name: "Girls Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 48,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img9.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kids",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683da147f779795ecfa98f7",
        name: "Women Zip-Front Relaxed Fit Jacket",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 78,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img44.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Women",
        stock: 100,
        isFeatured: true,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d91f7f779795ecfa98eb",
        name: "Men Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 48,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img14.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Men",
        stock: 95,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683db0d7f779795ecfa9907",
        name: "Men Slim Fit Relaxed Denim Jacket",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 84,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img52.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Men",
        stock: 61,
        isFeatured: true,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d42b7f779795ecfa98a5",
        name: "Girls Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 50,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img3.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kids",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d6dc7f779795ecfa98cb",
        name: "Women Palazzo Pants with Waist Belt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 67,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img22.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Women",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d5987f779795ecfa98b9",
        name: "Women Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 45,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img13.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Women",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d6057f779795ecfa98bf",
        name: "Girls Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 40,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img16.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kids",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d8467f779795ecfa98dd",
        name: "Men Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 34,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img31.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Men",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d90a7f779795ecfa98e9",
        name: "Women Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 42,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img13.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Women",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d9fa7f779795ecfa98f5",
        name: "Kid Tapered Slim Fit Trouser",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 60,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img43.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kids",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683daa27f779795ecfa98ff",
        name: "Men Slim Fit Relaxed Denim Jacket",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 80,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img48.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Men",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d8b37f779795ecfa98e3",
        name: "Women Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 38,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img34.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Women",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d6547f779795ecfa98c3",
        name: "Boy Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 28,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img18.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kids",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d4f47f779795ecfa98af",
        name: "Men Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 68,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img8.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Men",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d57d7f779795ecfa98b7",
        name: "Men Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 26,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img12.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Men",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d6387f779795ecfa98c1",
        name: "Men Tapered Fit Flat-Front Trousers",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 63,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img17.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Men",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d6c47f779795ecfa98c9",
        name: "Women Zip-Front Relaxed Fit Jacket",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 82,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img21.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Women",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683da717f779795ecfa98fb",
        name: "Men Slim Fit Relaxed Denim Jacket",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 72,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img46.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Men",
        stock: 100,
        isFeatured: true,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d7b57f779795ecfa98d5",
        name: "Girls Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 38,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img3.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kids",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d3947f779795ecfa98a1",
        name: "Women Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 40,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img1.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Women",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d4587f779795ecfa98a7",
        name: "Men Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 26,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img4.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Men",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d7567f779795ecfa98cf",
        name: "Boy Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 30,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img24.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kids",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d79e7f779795ecfa98d3",
        name: "Women Zip-Front Relaxed Fit Jacket",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 82,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img26.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Women",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d7d57f779795ecfa98d7",
        name: "Men Slim Fit Relaxed Denim Jacket",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 79,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img28.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Men",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d8f27f779795ecfa98e7",
        name: "Women Zip-Front Relaxed Fit Jacket",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 78,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img36.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Women",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d94e7f779795ecfa98ed",
        name: "Men Printed Plain Cotton Shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 52,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img39.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Men",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683dadf7f779795ecfa9903",
        name: "Kid Tapered Slim Fit Trouser",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 40,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img50.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kids",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683daf67f779795ecfa9905",
        name: "Women Zip-Front Relaxed Fit Jacket",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 68,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img51.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Women",
        stock: 100,
        isFeatured: true,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d4b27f779795ecfa98ab",
        name: "Girls Round Neck Cotton Top",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 56,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img6.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kids",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d5e07f779795ecfa98bd",
        name: "Men Tapered Fit Flat-Front Trousers",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 58,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img15.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Men",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d8d17f779795ecfa98e5",
        name: "Women Zip-Front Relaxed Fit Jacket",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 74,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img35.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Women",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d5b67f779795ecfa98bb",
        name: "Boy Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 60,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img14.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kids",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d8897f779795ecfa98df",
        name: "Men Round Neck Pure Cotton T-shirt",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 64,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img8.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Men",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683da887f779795ecfa98fd",
        name: "Kid Tapered Slim Fit Trouser",
        description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
        price: 38,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img47.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kids",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
];

export const dummyAddress = [
    {
        _id: "6985ab44a309ee0204588085",
        user: "69819801a872c913f84d13f4",
        type: "Home",
        street: "124 Main Street , Volley Market",
        city: "New York",
        state: "NY",
        zipCode: "100001",
        country: "USA",
        isDefault: false,
        createdAt: "2026-02-06T08:50:12.856Z",
    },
    {
        _id: "6985ab44a309ee0204588086",
        user: "69819801a872c913f84d13f4",
        type: "Office",
        street: "Z Block, Millin Street",
        city: "New York",
        state: "NY",
        zipCode: "100001",
        country: "USA",
        isDefault: false,
        createdAt: "2026-02-06T08:50:12.856Z",
    },
];

export const dummyUser = {
    _id: "69819801a872c913f84d13f4",
    name: "John Doe",
    email: "john@example.com",
    firstName: "John",
    lastName: "Doe",
    imageUrl: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=240",
    emailAddresses: [
        {
            emailAddress: "john@example.com",
        },
    ],
    clerkId: "user_396E235",
    role: "admin",
    publicMetadata: {
        role: "admin",
    },
};

export const dummyCart = {
    _id: "6984434e30be1ba0cf5d0fd4",
    user: "69819801a872c913f84d13f4",
    items: [
        {
            product: {
                _id: "6683d91f7f779795ecfa98eb",
                name: "Men Round Neck Pure Cotton T-shirt",
                price: 48,
                images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img14.png"],
                stock: 95,
            },
            quantity: 1,
            price: 48,
            size: "M",
            _id: "698952e1ef9d0c746ef827b9",
        },
        {
            product: {
                _id: "6683d4f47f779795ecfa98af",
                name: "Men Round Neck Pure Cotton T-shirt",
                price: 68,
                images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img8.png"],
                stock: 100,
            },
            quantity: 1,
            price: 68,
            size: "L",
            _id: "698952f5ef9d0c746ef827c6",
        },
    ],
    totalAmount: 116,
    createdAt: "2026-02-05T07:14:22.429Z",
};

export const dummyWishlist = [dummyProducts[3], dummyProducts[10], dummyProducts[6]];

export const dummyOrders = [
    {
        shippingAddress: {
            street: "124 Main Street , Volley Market",
            city: "New York",
            state: "NY",
            zipCode: "100001",
            country: "USA",
        },
        _id: "69895582ef9d0c746ef82849",
        user: "69819801a872c913f84d13f4",
        items: [
            {
                product: dummyProducts[6],
                name: dummyProducts[6].name,
                quantity: 1,
                price: dummyProducts[6].price,
                size: "L",
                _id: "69895582ef9d0c746ef8284a",
            },
            {
                product: dummyProducts[10],
                name: dummyProducts[10].name,
                quantity: 1,
                price: 28,
                size: "L",
                _id: "69895582ef9d0c746ef8284b",
            },
        ],
        paymentMethod: "stripe",
        paymentStatus: "paid",
        orderStatus: "placed",
        subtotal: 88,
        shippingCost: 2,
        tax: 0,
        totalAmount: 90,
        notes: "Placed via App",
        createdAt: "2026-02-09T03:33:22.261Z",
        orderNumber: "ORD-1770608002261",
        paymentIntentId: "pi_3SylEFFwJO8iCzjO1DHedE7e",
    },
    {
        shippingAddress: {
            street: "124 Main Street , Volley Market",
            city: "New York",
            state: "NY",
            zipCode: "100001",
            country: "USA",
        },
        _id: "69895557ef9d0c746ef8280d",
        user: "69819801a872c913f84d13f4",
        items: [
            {
                product: dummyProducts[14],
                name: dummyProducts[14].name,
                quantity: 1,
                price: dummyProducts[14].price,
                size: "M",
                _id: "69895557ef9d0c746ef8280e",
            },
            {
                product: dummyProducts[10],
                name: dummyProducts[10].name,
                quantity: 1,
                price: dummyProducts[10].price,
                size: "L",
                _id: "69895557ef9d0c746ef8280f",
            },
        ],
        paymentMethod: "cash",
        paymentStatus: "pending",
        orderStatus: "placed",
        subtotal: 116,
        shippingCost: 2,
        tax: 0,
        totalAmount: 118,
        notes: "Placed via App",
        createdAt: "2026-02-09T03:32:39.510Z",
        orderNumber: "ORD-1770607959511",
    },
];

export const dummyAdminStats = {
    totalUsers: 3,
    totalProducts: 60,
    totalOrders: 4,
    totalRevenue: 380,
    recentOrders: dummyOrders,
};
